spring.application.name=supportsystem
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=healthcare_support;encrypt=false
spring.datasource.username=appuser
spring.datasource.password=AppUser@123
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
