spring.application.name=supportsystem
# SQL Server connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=healthcare_support;encrypt=false
spring.datasource.username=appuser
spring.datasource.password=AppUser@123


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQL Server dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
